name: link_manager
description: A new Flutter project.
publish_to: 'none'
# new_version
version: 2.2.0+19

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.29.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # logic
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  provider: ^6.0.5
  connectivity_plus: ^6.1.2
  shared_preferences: ^2.3.2

  # firebase + google services
  google_sign_in: ^6.2.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  # decorations
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1

  url_launcher: ^6.1.14
  clipboard: ^0.1.3
  auto_size_text: ^3.0.0
  animated_flip_counter: ^0.3.4
  flutter_slidable: ^4.0.0
  http: ^1.3.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  intl_utils: ^2.8.7
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
flutter_intl:
  enabled: true
