name: link_manager
description: A new Flutter project.
publish_to: 'none'
# new_version
version: 2.1.4+13

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # logic
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  connectivity_plus: ^6.0.1
  
  # firebase + google sevices
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.8
  # decorations
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  
  url_launcher: ^6.1.14
  great_list_view: ^0.2.3
  clipboard: ^0.1.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
