name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Create firebase_options.dart
        env:
          FIREBASE_OPTIONS_FILE: ${{ secrets.FIREBASE_OPTIONS_FILE }}  # Секретная переменная с содержимым файла
        run: |
          # Создаем файл firebase_options.dart из секрета
          echo "$FIREBASE_OPTIONS_FILE" > lib/firebase_options.dart

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Upload iOS Build
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
